# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1SO7dzF_z0uTm4NwZFVctiuHXV8hmwV
"""

#Q1
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

linear_svm = SVC(kernel="linear")
poly_svm = SVC(kernel="poly", degree=3)
rbf_svm = SVC(kernel="rbf")

models = [("Linear Kernel", linear_svm), ("Polynomial Kernel", poly_svm), ("RBF Kernel", rbf_svm)]

for name, model in models:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print("\n", name)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, average='macro'))
    print("Recall:", recall_score(y_test, y_pred, average='macro'))
    print("F1 Score:", f1_score(y_test, y_pred, average='macro'))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

#Q2
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

svm_no_scale = SVC(kernel='rbf')
svm_no_scale.fit(X_train, y_train)
train_no = svm_no_scale.score(X_train, y_train)
test_no = svm_no_scale.score(X_test, y_test)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

svm_scaled = SVC(kernel='rbf')
svm_scaled.fit(X_train_s, y_train)
train_scaled = svm_scaled.score(X_train_s, y_train)
test_scaled = svm_scaled.score(X_test_s, y_test)

print("\nSVM Performance Comparison")
print("Without Scaling -> Train:", train_no, "Test:", test_no)
print("With Scaling    -> Train:", train_scaled, "Test:", test_scaled)